### ISSUE TITLE
Add functionality to compare weekly/monthly expenses 

### ISSUE THREAD

**Issue by tpanati** [tpanati/DollarBot#14]
Add the following commands:

1. /weekly: this command when called gives an analysis report that compares weekly expenditures for overall total cost and total cost for each category.
2. /monthly: this command when called gives an analysis report that compares monthly expenditures for overall total cost and total cost for each category.

**Comment by vyshnavi-adusumelli** [comment]
Created pull request for this issue

https://github.com/tpanati/DollarBot/pull/26
