### ISSUE TITLE
Resolve an issue with add functionality when budget is not set and you add an expense

### ISSUE THREAD

**Issue by tpanati** [tpanati/DollarBot#16]
![image](https://github.com/tpanati/DollarBot/assets/144171816/32664523-068f-4382-9a16-223e960f220b)

Looks like if budget is not set and we add an expense it shows the exception.

Line number : 134 in add.py

**Comment by vyshnavi-adusumelli** [comment]
Recreated the issue in my local and adding telegram conversation here

<img width="907" alt="Screenshot 2023-11-14 at 2 19 05 PM" src="https://github.com/tpanati/DollarBot/assets/35067896/f76a08a4-2022-4465-8961-b61f0cf6d8bf">

<img width="906" alt="Screenshot 2023-11-14 at 2 19 27 PM" src="https://github.com/tpanati/DollarBot/assets/35067896/3466d56e-a2f5-4309-aacb-4bce34faae3b">

**Comment by vyshnavi-adusumelli** [comment]
Raised a pr for the issue https://github.com/tpanati/DollarBot/pull/39
