### ISSUE TITLE
Implement test cases for the failure scenarios in add functionality/ command

### ISSUE THREAD

**Issue by tpanati** [tpanati/DollarBot#43]
There is an issue where the test cases for an edge case in post_amount_input in add functionality is not implemented. Creating this issue to track it.

https://github.com/tpanati/DollarBot/actions/runs/6897202860/job/18764887566

![image](https://github.com/tpanati/DollarBot/assets/144171816/728732a4-e401-4f0c-8aac-e075d4e8758c)

![image](https://github.com/tpanati/DollarBot/assets/144171816/cd347247-1bc1-45d9-88bf-b112d7039a8d)

![image](https://github.com/tpanati/DollarBot/assets/144171816/e5881c79-a355-4f37-a1f2-696c54410d1c)

**Comment by hbandar** [comment]
Resolved this issue in CI pipeline - https://github.com/tpanati/DollarBot/pull/51
